
var blocks = {
    ifcondition:'@{ if Recipient.IsInSegment("place")}',
    elseifcondition:'@{else if Recipient.IsInSegment("place")}',
    endif:"@{end if}",
    else:"@{else}",
    start: `<table cellpadding="0" cellspacing="0" class="es-content" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%"><tr><td align="center" style="padding:0;Margin:0"><table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:690px"><tr><td class="es-m-p20r es-m-p20l" align="left" style="padding:0;Margin:0;padding-left:40px;padding-right:40px;padding-bottom:REPpx">`,
    Articles_DBaaS: `<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr>
    <td class="es-m-p0r" align="center" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;border-left:2px solid #0e0d0d;border-right:2px solid #0e0d0d;border-top:2px solid #0e0d0d;border-bottom:2px solid #0e0d0d;border-radius:20px"><tr>
    <td align="center" class="es-m-txt-l es-m-p10l" style="padding:0;Margin:0;padding-top:15px;font-size:0px"><a target="_blank" href="https://habr.com/ru/company/selectel/blog/703460/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_e958d8c72af43af64fc915321e414a6c6fbb2fbe7a5dc4b7c0f88d069276aaa4/images/mlop.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="118" height="70"></a> </td></tr><tr>
    <td align="left" class="es-m-p10l" style="padding:0;Margin:0;padding-top:5px;padding-bottom:15px;padding-left:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://habr.com/ru/company/selectel/blog/703460/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">СТАТЬЯ</a></strong></p></td></tr></table></td></tr></table> `,
    DBaaS: `<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr>
    <td class="es-m-p0r" align="center" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;border-left:2px solid #0e0d0d;border-right:2px solid #0e0d0d;border-top:2px solid #0e0d0d;border-bottom:2px solid #0e0d0d;border-radius:20px"><tr>
    <td align="center" class="es-m-txt-l es-m-p10l" style="padding:0;Margin:0;padding-top:15px;font-size:0px"><a target="_blank" href="https://habr.com/ru/company/selectel/blog/703460/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_e958d8c72af43af64fc915321e414a6c6fbb2fbe7a5dc4b7c0f88d069276aaa4/images/mlop.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="118" height="70"></a> </td></tr><tr>
    <td align="left" class="es-m-p10l" style="padding:0;Margin:0;padding-top:5px;padding-bottom:15px;padding-left:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://habr.com/ru/company/selectel/blog/703460/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">ПРОДУКТ</a></strong></p></td></tr></table></td></tr></table> `,
    
    probel: `<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr>
    <td align="center" style="padding:0;Margin:0;width:10px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><br></p></td></tr></table></td></tr></table>`,
    end:'</td></tr></table></td></tr></table>'
    // Добавьте нужные вам переменные
  };
