
var blocks = {
    ifcondition:'@{ if Recipient.IsInSegment("place")}',
    elseifcondition:'@{else if Recipient.IsInSegment("place")}',
    endif:"@{end if}",
    else:"@{else}",
    start: `<table cellpadding="0" cellspacing="0" class="es-content" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%"><tr><td align="center" style="padding:0;Margin:0"><table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:690px">
    <tr>
    <td class="es-m-p20r es-m-p20l" align="left" bgcolor="#ffffff" style="Margin:0;padding-bottom:20px;padding-top:0px;padding-left:80px;padding-right:80px;background-color:#ffffff;border-radius:25px 25px 0px 0px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="left" style="padding:0;Margin:0;width:530px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="left" style="padding:0;Margin:0"><h1 style="Margin:0;line-height:29px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:24px;font-style:normal;font-weight:600;color:ROPP">Вам может быть интересно</h1> </td></tr></tbody></table></td></tr></tbody></table></td></tr>
    <tr><td class="es-m-p20r es-m-p20l" align="left" style="padding:0;Margin:0;padding-left:40px;padding-right:40px;padding-bottom:REPpx">`,
    Articles_Base1: `<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
    <td class="es-m-p0r es-m-p20b" align="center" style="padding:0;Margin:0;width:195px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0 es-m-txt-l" style="padding:0;Margin:0;padding-left:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/digest01_24/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_1321316183112.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="155" height="94"></a> </td></tr><tr>
    <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/digest01_24/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Наши продуктовые обновления за&nbsp;2023 год</a></strong></p></td></tr></tbody></table></td></tr></tbody></table> `,
    
    Articles_Base2: `<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
    <td class="es-m-p20b" align="center" style="padding:0;Margin:0;width:191px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/neuronet-for-employees/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_1321316183122.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="158" height="95"></a> </td></tr><tr>
    <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:20px;padding-right:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/neuronet-for-employees/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Как нейросети облегчают работу IT&#8209;специалистов</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
    Articles_Base3: `<table cellpadding="0" cellspacing="0" class="es-right" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tbody><tr>
    <td align="center" style="padding:0;Margin:0;width:194px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0r es-m-txt-l" style="padding:0;Margin:0;padding-right:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/digital-hygiene/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_13213161831322.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="154" height="93"></a> </td></tr><tr>
    <td align="left" style="padding:0;Margin:0;padding-top:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><u><strong><a target="_blank" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#092433;font-size:16px" href="https://selectel.ru/blog/digital-hygiene/">Цифровая гигиена: определение и&nbsp; рекомендации</a></strong></u></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
    Dedicated: `<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td class="es-m-p20b" align="left" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:20px;border-width:1px;border-color:#0e0d0d;border-style:solid"><tr>
    <td align="center" style="padding:0;Margin:0;padding-top:15px;padding-left:15px;font-size:0px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_860deba2f44fc3fa083120fe12d0655cf28aca489f5bca0bfbb6c329da858fce/images/servers_multiple.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="25" height="25"></td> <td align="left" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-top:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><b>Выделенные серверы</b></p></td></tr><tr>
    <td align="left" colspan="2" style="padding:15px;Margin:0"><h2 style="Margin:0;line-height:14px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:12px;font-style:normal;font-weight:normal;color:#092433">Выбирайте готовые и&nbsp;кастомные модели.</h2></td></tr> <tr>
    <td align="left" colspan="2" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-bottom:20px"><span class="es-button-border" style="border-style:solid;border-color:#eb4247;background:#ffffff;border-width:1px;display:inline-block;border-radius:10px;width:auto"><a href="https://selectel.ru/services/dedicated/" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#eb4247;font-size:16px;display:inline-block;background:#FFFFFF;border-radius:10px;font-family:Manrope, sans-serif, 'font family';font-weight:normal;font-style:normal;line-height:19px;width:auto;text-align:center;padding:10px 20px 10px 20px;mso-padding-alt:0;mso-border-alt:10px solid #FFFFFF"> Подробнее </a></span></td></tr></table></td></tr></table>`,
    Storage: `<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td class="es-m-p20b" align="left" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:20px;border-width:1px;border-color:#0e0d0d;border-style:solid"><tr><td align="center" style="padding:0;Margin:0;padding-top:15px;padding-left:15px;font-size:0px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_860deba2f44fc3fa083120fe12d0655cf28aca489f5bca0bfbb6c329da858fce/images/folder.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="25" height="25"></td>
    <td align="left" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-top:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><b>Объектное хранилище</b></p></td></tr><tr><td align="left" colspan="2" style="padding:15px;Margin:0"><h2 style="Margin:0;line-height:14px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:12px;font-style:normal;font-weight:normal;color:#092433">Храните данные, бэкапы и&nbsp;контент.</h2></td></tr> <tr>
   <td align="left" colspan="2" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-bottom:20px"><span class="es-button-border" style="border-style:solid;border-color:#eb4247;background:#ffffff;border-width:1px;display:inline-block;border-radius:10px;width:auto"><a href="https://selectel.ru/services/cloud/storage/" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#eb4247;font-size:16px;display:inline-block;background:#FFFFFF;border-radius:10px;font-family:Manrope, sans-serif, 'font family';font-weight:normal;font-style:normal;line-height:19px;width:auto;text-align:center;padding:10px 20px 10px 20px;mso-padding-alt:0;mso-border-alt:10px solid #FFFFFF"> Подробнее </a></span></td></tr></table></td></tr></table>`,
    Kuber:`<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:20px;border-width:1px;border-color:#0e0d0d;border-style:solid"><tr><td align="center" style="padding:0;Margin:0;padding-top:15px;padding-left:15px;font-size:0px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_860deba2f44fc3fa083120fe12d0655cf28aca489f5bca0bfbb6c329da858fce/images/k8s.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="25" height="25"></td>
    <td align="left" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-top:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><b>Managed Kubernetes</b></p></td></tr><tr><td align="left" colspan="2" style="padding:15px;Margin:0"><h2 style="Margin:0;line-height:14px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:12px;font-style:normal;font-weight:normal;color:#092433">Управляйте кластерами с&nbsp;гарантией доступности.</h2></td></tr> <tr>
   <td align="left" colspan="2" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-bottom:20px"><span class="es-button-border" style="border-style:solid;border-color:#eb4247;background:#ffffff;border-width:1px;display:inline-block;border-radius:10px;width:auto"><a href="https://selectel.ru/services/cloud/kubernetes/" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#eb4247;font-size:16px;display:inline-block;background:#FFFFFF;border-radius:10px;font-family:Manrope, sans-serif, 'font family';font-weight:normal;font-style:normal;line-height:19px;width:auto;text-align:center;padding:10px 20px 10px 20px;mso-padding-alt:0;mso-border-alt:10px solid #FFFFFF"> Подробнее </a></span></td></tr></table></td></tr></table>`,
    Cloud:`<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td class="es-m-p20b" align="left" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:20px;border-width:1px;border-color:#0e0d0d;border-style:solid"><tr><td align="center" style="padding:0;Margin:0;padding-top:15px;padding-left:15px;font-size:0px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_860deba2f44fc3fa083120fe12d0655cf28aca489f5bca0bfbb6c329da858fce/images/cloud_multi.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="25" height="25"></td>
    <td align="left" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-top:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><b>Облачные серверы</b></p></td></tr><tr><td align="left" colspan="2" style="padding:15px;Margin:0"><h2 style="Margin:0;line-height:14px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:12px;font-style:normal;font-weight:normal;color:#092433">Запустите виртуальную машину за&nbsp;минуту.</h2></td></tr> <tr>
   <td align="left" colspan="2" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-bottom:20px"><span class="es-button-border" style="border-style:solid;border-color:#eb4247;background:#ffffff;border-width:1px;display:inline-block;border-radius:10px;width:auto"><a href="https://selectel.ru/services/cloud/servers/" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#eb4247;font-size:16px;display:inline-block;background:#FFFFFF;border-radius:10px;font-family:Manrope, sans-serif, 'font family';font-weight:normal;font-style:normal;line-height:19px;width:auto;text-align:center;padding:10px 20px 10px 20px;mso-padding-alt:0;mso-border-alt:10px solid #FFFFFF"> Подробнее </a></span></td></tr></table></td> </tr></table>`,
    CDN: `<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:20px;border-width:1px;border-color:#0e0d0d;border-style:solid"><tr><td align="center" style="padding:0;Margin:0;padding-top:15px;font-size:0px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_860deba2f44fc3fa083120fe12d0655cf28aca489f5bca0bfbb6c329da858fce/images/cloud_download.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="25" height="25"></td>
    <td align="left" class="es-m-p20t es-m-p0b" style="padding:0;Margin:0;padding-bottom:15px;padding-top:30px;padding-right:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><b>CDN</b></p></td></tr><tr><td align="left" colspan="2" style="padding:15px;Margin:0"><h2 style="Margin:0;line-height:14px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:12px;font-style:normal;font-weight:normal;color:#092433">Ускоряйте загрузку и&nbsp;раздачу контента.</h2></td></tr> <tr>
   <td align="left" colspan="2" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-bottom:20px"><span class="es-button-border" style="border-style:solid;border-color:#eb4247;background:#ffffff;border-width:1px;display:inline-block;border-radius:10px;width:auto"><a href="https://selectel.ru/services/additional/cdn/" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#eb4247;font-size:16px;display:inline-block;background:#FFFFFF;border-radius:10px;font-family:Manrope, sans-serif, 'font family';font-weight:normal;font-style:normal;line-height:19px;width:auto;text-align:center;padding:10px 20px 10px 20px;mso-padding-alt:0;mso-border-alt:10px solid #FFFFFF"> Подробнее </a></span></td></tr></table></td></tr></table>`,
    Firewall: `<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:20px;border-width:1px;border-color:#0e0d0d;border-style:solid"><tr><td align="center" style="padding:0;Margin:0;padding-top:15px;padding-left:15px;font-size:0px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_860deba2f44fc3fa083120fe12d0655cf28aca489f5bca0bfbb6c329da858fce/images/shield.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="25" height="25"></td>
    <td align="left" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-top:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><b>Бесплатный файрвол</b></p></td></tr><tr><td align="left" colspan="2" style="padding:15px;Margin:0"><h2 style="Margin:0;line-height:14px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:12px;font-style:normal;font-weight:normal;color:#092433">Фильтруйте нежелательный трафик.</h2></td></tr> <tr>
   <td align="left" colspan="2" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-bottom:20px"><span class="es-button-border" style="border-style:solid;border-color:#eb4247;background:#ffffff;border-width:1px;display:inline-block;border-radius:10px;width:auto"><a href="https://docs.selectel.ru/cloud/servers/firewalls/about-firewalls/" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#eb4247;font-size:16px;display:inline-block;background:#FFFFFF;border-radius:10px;font-family:Manrope, sans-serif, 'font family';font-weight:normal;font-style:normal;line-height:19px;width:auto;text-align:center;padding:10px 20px 10px 20px;mso-padding-alt:0;mso-border-alt:10px solid #FFFFFF"> Подробнее </a></span></td></tr></table></td></tr></table>`,
    Router:`<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" style="padding:0;Margin:0;width:190px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:20px;border-width:1px;border-color:#0e0d0d;border-style:solid"><tr><td align="center" style="padding:0;Margin:0;padding-top:15px;padding-left:15px;font-size:0px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_860deba2f44fc3fa083120fe12d0655cf28aca489f5bca0bfbb6c329da858fce/images/dots_fork.png" alt style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="25" height="25"></td>
    <td align="left" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-top:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><b>Глобальный роутер</b></p></td></tr><tr><td align="left" colspan="2" style="padding:15px;Margin:0"><h2 style="Margin:0;line-height:14px;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';font-size:12px;font-style:normal;font-weight:normal;color:#092433">Свяжите облачные и&nbsp;физические серверы.</h2></td></tr> <tr>
   <td align="left" colspan="2" style="padding:0;Margin:0;padding-left:15px;padding-right:15px;padding-bottom:20px"><span class="es-button-border" style="border-style:solid;border-color:#eb4247;background:#ffffff;border-width:1px;display:inline-block;border-radius:10px;width:auto"><a href="https://selectel.ru/services/additional/local-network/" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#eb4247;font-size:16px;display:inline-block;background:#FFFFFF;border-radius:10px;font-family:Manrope, sans-serif, 'font family';font-weight:normal;font-style:normal;line-height:19px;width:auto;text-align:center;padding:10px 20px 10px 20px;mso-padding-alt:0;mso-border-alt:10px solid #FFFFFF"> Подробнее </a></span></td></tr></table></td></tr></table>`,
    
    Articles_Dedicated1:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
    <td class="es-m-p0r es-m-p20b" align="center" style="padding:0;Margin:0;width:195px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0 es-m-txt-l" style="padding:0;Margin:0;padding-left:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/auction-of-servers/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618382.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="155" height="94"></a> </td></tr><tr>
    <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/auction-of-servers/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Как работает аукцион серверов</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Dedicated2:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p20b" align="center" style="padding:0;Margin:0;width:191px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/migration-servers/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618392.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="158" height="95"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/migration-servers/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Как провести миграцию серверов, пока клиенты спят</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Dedicated3:`<table cellpadding="0" cellspacing="0" class="es-right" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tbody><tr>
   <td align="center" style="padding:0;Margin:0;width:194px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0r es-m-txt-l" style="padding:0;Margin:0;padding-right:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/basic-firewall/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_1321316183102.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="154" height="93"></a> </td></tr><tr>
   <td align="left" style="padding:0;Margin:0;padding-top:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><u><strong><a target="_blank" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#092433;font-size:16px" href="https://selectel.ru/blog/basic-firewall/">Когда вам достаточно базового файрвола</a></strong></u></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_DBaaS1:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr><td class="es-m-p0r es-m-p20b" align="center" style="padding:0;Margin:0;width:195px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr>
   <td align="center" class="es-m-p0 es-m-txt-l" style="padding:0;Margin:0;padding-left:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/courses/postgresql-for-beginners/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_13213161832.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="155" height="94"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/courses/postgresql-for-beginners/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Курс &laquo;PostgreSQL для новичков&raquo;</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_DBaaS2:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p20b" align="center" style="padding:0;Margin:0;width:191px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/infrastructure-with-db/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618332.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="158" height="95"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/infrastructure-with-db/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Организация инфраструктуры с&nbsp;базами данных</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_DBaaS3:`<table cellpadding="0" cellspacing="0" class="es-right" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tbody><tr>
   <td align="center" style="padding:0;Margin:0;width:194px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0r es-m-txt-l" style="padding:0;Margin:0;padding-right:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/apache-kafka-2/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618342.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="154" height="93"></a> </td></tr><tr>
   <td align="left" style="padding:0;Margin:0;padding-top:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><u><strong><a target="_blank" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#092433;font-size:16px" href="https://selectel.ru/blog/apache-kafka-2/">Apache Kafka: в&nbsp;теории и&nbsp;на&nbsp;практике</a></strong></u></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Colocation1:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p0r es-m-p20b" align="center" style="padding:0;Margin:0;width:195px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0 es-m-txt-l" style="padding:0;Margin:0;padding-left:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/case-cupis/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618352.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="155" height="94"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/case-cupis/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Кейс крупного Fintech-проекта</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Colocation2:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p20b" align="center" style="padding:0;Margin:0;width:191px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/network-reservation/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618362.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="158" height="95"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/network-reservation/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Сетевое резервирование в&nbsp;дата-центрах</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Colocation3:`<table cellpadding="0" cellspacing="0" class="es-right" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tbody><tr>
   <td align="center" style="padding:0;Margin:0;width:194px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0r es-m-txt-l" style="padding:0;Margin:0;padding-right:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/fault-tolerant-infrastructure/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618372.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="154" height="93"></a> </td></tr><tr>
   <td align="left" style="padding:0;Margin:0;padding-top:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><u><strong><a target="_blank" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#092433;font-size:16px" href="https://selectel.ru/blog/fault-tolerant-infrastructure/">Организация отказоустойчивой IT&#8209;инфраструктуры</a></strong></u></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_CDN1:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr><td class="es-m-p0r es-m-p20b" align="center" style="padding:0;Margin:0;width:195px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr>
   <td align="center" class="es-m-p0 es-m-txt-l" style="padding:0;Margin:0;padding-left:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/courses/network-security/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_13213161832_J5A.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="155" height="94"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/courses/network-security/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Курс &laquo;Введение в&nbsp;сетевую безопасность&raquo;</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_CDN2:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p20b" align="center" style="padding:0;Margin:0;width:191px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/antiddos_cdn/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618332_tHR.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="158" height="95"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/antiddos_cdn/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">CDN против DDoS&#8209;атак</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_CDN3:`<table cellpadding="0" cellspacing="0" class="es-right" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tbody><tr>
   <td align="center" style="padding:0;Margin:0;width:194px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0r es-m-txt-l" style="padding:0;Margin:0;padding-right:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/project-naas/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618342_4sA.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="154" height="93"></a> </td></tr><tr>
   <td align="left" style="padding:0;Margin:0;padding-top:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><u><strong><a target="_blank" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#092433;font-size:16px" href="https://selectel.ru/blog/project-naas/">Как мы&nbsp;запустили глобальный роутер</a></strong></u></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Storage1:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p0r es-m-p20b" align="center" style="padding:0;Margin:0;width:195px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0 es-m-txt-l" style="padding:0;Margin:0;padding-left:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/cloud-storage/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618362_gXk.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="155" height="94"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/cloud-storage/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Как работают объектные хранилища</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Storage2:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p20b" align="center" style="padding:0;Margin:0;width:191px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/wfolio/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618332_Z8A.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="158" height="95"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:20px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><u><strong><a target="_blank" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#092433;font-size:16px" href="https://selectel.ru/blog/wfolio/">Кейс хранилища на 1,5 петабайт данных</a></strong></u></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Storage3:`<table cellpadding="0" cellspacing="0" class="es-right" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tbody><tr>
   <td align="center" style="padding:0;Margin:0;width:194px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;padding-right:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/data-warehouse/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_13213161832_xjS.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="154" height="93"></a> </td></tr><tr>
   <td align="left" style="padding:0;Margin:0;padding-top:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/data-warehouse/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Хранилище данных Data Warehouse: зачем оно бизнесу</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Cloud1:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p0r es-m-p20b" align="center" style="padding:0;Margin:0;width:195px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0 es-m-txt-l" style="padding:0;Margin:0;padding-left:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/keys-imredy/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618342_Vet.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="155" height="94"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:40px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/keys-imredy/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Платформа на&nbsp;50&nbsp;000 сотрудников</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Cloud2:`<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tbody><tr>
   <td class="es-m-p20b" align="center" style="padding:0;Margin:0;width:191px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-txt-l" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/certified-cloud/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618352_Fcb.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="158" height="95"></a> </td></tr><tr>
   <td align="left" class="es-m-p0l" style="padding:0;Margin:0;padding-top:5px;padding-left:20px;padding-right:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><strong><a target="_blank" href="https://selectel.ru/blog/certified-cloud/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px">Аттестованное облако при работе с&nbsp;ГИС</a></strong></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   Articles_Cloud3:`<table cellpadding="0" cellspacing="0" class="es-right" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tbody><tr>
   <td align="center" style="padding:0;Margin:0;width:194px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" class="es-m-p0r es-m-txt-l" style="padding:0;Margin:0;padding-right:40px;font-size:0px"><a target="_blank" href="https://selectel.ru/blog/cloud-firewall/" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#092433;font-size:16px"><img src="https://kllifs.stripocdn.email/content/guids/CABINET_ba947cda5dbf87c64f6f3b2254e50b776569bbe09498ca1859bffe39b0938ca0/images/frame_132131618372_WUv.png" alt="" style="display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic" width="154" height="93"></a> </td></tr><tr>
   <td align="left" style="padding:0;Margin:0;padding-top:5px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><u><strong><a target="_blank" style="-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#092433;font-size:16px" href="https://selectel.ru/blog/cloud-firewall/">Облачный файрвол Selectel: как защитить сеть за&nbsp;пару кликов</a></strong></u></p></td></tr></tbody></table></td></tr></tbody></table>`,
    
   
   probel: `<table cellpadding="0" cellspacing="0" class="es-left" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr>
    <td align="center" style="padding:0;Margin:0;width:10px"><table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif, 'font family';line-height:24px;color:#092433;font-size:16px"><br></p></td></tr></table></td></tr></table>`,
    end:'</td></tr></table></td></tr></table>'
    // Добавьте нужные вам переменные
  };
